# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(808, 564)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 769, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.search_with_combo = QtWidgets.QComboBox(self.layoutWidget)
        self.search_with_combo.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.search_with_combo.setObjectName("search_with_combo")
        self.search_with_combo.addItem("")
        self.search_with_combo.addItem("")
        self.horizontalLayout.addWidget(self.search_with_combo)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.search_button = QtWidgets.QPushButton(self.layoutWidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sortby_combo = QtWidgets.QComboBox(self.layoutWidget)
        self.sortby_combo.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.sortby_combo.setObjectName("sortby_combo")
        self.sortby_combo.addItem("")
        self.sortby_combo.addItem("")
        self.horizontalLayout.addWidget(self.sortby_combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.all_dictionary = QtWidgets.QListWidget(self.layoutWidget)
        self.all_dictionary.setObjectName("all_dictionary")
        self.verticalLayout.addWidget(self.all_dictionary)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "SEARCH"))
        self.search_with_combo.setItemText(0, _translate("Dialog", "by name"))
        self.search_with_combo.setItemText(1, _translate("Dialog", "by sentences"))
        self.search_button.setText(_translate("Dialog", "SEARCH"))
        self.label.setText(_translate("Dialog", "SORT"))
        self.sortby_combo.setItemText(0, _translate("Dialog", "by added date"))
        self.sortby_combo.setItemText(1, _translate("Dialog", "by name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
