# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_algorithm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DesignAlgorithm(object):
    def setupUi(self, DesignAlgorithm):
        DesignAlgorithm.setObjectName("DesignAlgorithm")
        DesignAlgorithm.resize(760, 791)
        self.centralwidget = QtWidgets.QWidget(DesignAlgorithm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.all_input = QtWidgets.QListWidget(self.centralwidget)
        self.all_input.setObjectName("all_input")
        self.verticalLayout_2.addWidget(self.all_input)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.add_input_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_input_button.setObjectName("add_input_button")
        self.verticalLayout_5.addWidget(self.add_input_button)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.all_layer = QtWidgets.QListWidget(self.centralwidget)
        self.all_layer.setObjectName("all_layer")
        self.verticalLayout.addWidget(self.all_layer)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.add_layer = QtWidgets.QPushButton(self.centralwidget)
        self.add_layer.setObjectName("add_layer")
        self.verticalLayout_4.addWidget(self.add_layer)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.view_compile = QtWidgets.QTextEdit(self.centralwidget)
        self.view_compile.setStyleSheet("font: 14pt \"Calibri\";")
        self.view_compile.setObjectName("view_compile")
        self.verticalLayout_8.addWidget(self.view_compile)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.add_compile = QtWidgets.QPushButton(self.centralwidget)
        self.add_compile.setObjectName("add_compile")
        self.verticalLayout_7.addWidget(self.add_compile)
        self.gridLayout.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.all_callback = QtWidgets.QListWidget(self.centralwidget)
        self.all_callback.setObjectName("all_callback")
        self.verticalLayout_10.addWidget(self.all_callback)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.add_callback_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_callback_button.setObjectName("add_callback_button")
        self.verticalLayout_9.addWidget(self.add_callback_button)
        self.gridLayout.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.add_algorithm = QtWidgets.QPushButton(self.centralwidget)
        self.add_algorithm.setStyleSheet("font: 14pt \"Calibri\";")
        self.add_algorithm.setObjectName("add_algorithm")
        self.gridLayout.addWidget(self.add_algorithm, 4, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        DesignAlgorithm.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DesignAlgorithm)
        self.statusbar.setObjectName("statusbar")
        DesignAlgorithm.setStatusBar(self.statusbar)

        self.retranslateUi(DesignAlgorithm)
        QtCore.QMetaObject.connectSlotsByName(DesignAlgorithm)

    def retranslateUi(self, DesignAlgorithm):
        _translate = QtCore.QCoreApplication.translate
        DesignAlgorithm.setWindowTitle(_translate("DesignAlgorithm", "MainWindow"))
        self.add_input_button.setText(_translate("DesignAlgorithm", "ADD INPUT"))
        self.add_layer.setText(_translate("DesignAlgorithm", "ADD LAYER"))
        self.view_compile.setHtml(_translate("DesignAlgorithm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.add_compile.setText(_translate("DesignAlgorithm", "SET COMPILE"))
        self.add_callback_button.setText(_translate("DesignAlgorithm", "ADD CALLBACK"))
        self.add_algorithm.setText(_translate("DesignAlgorithm", "GO"))
        self.pushButton.setText(_translate("DesignAlgorithm", "BACK"))
