# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_sentence_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeSentenceDialog(object):
    def setupUi(self, ChangeSentenceDialog):
        ChangeSentenceDialog.setObjectName("ChangeSentenceDialog")
        ChangeSentenceDialog.resize(508, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChangeSentenceDialog.sizePolicy().hasHeightForWidth())
        ChangeSentenceDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(ChangeSentenceDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ChangeSentenceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.word_name = QtWidgets.QTextEdit(ChangeSentenceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_name.sizePolicy().hasHeightForWidth())
        self.word_name.setSizePolicy(sizePolicy)
        self.word_name.setMaximumSize(QtCore.QSize(16777215, 39))
        self.word_name.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.word_name.setObjectName("word_name")
        self.horizontalLayout.addWidget(self.word_name)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(ChangeSentenceDialog)
        self.label_2.setMaximumSize(QtCore.QSize(151, 20))
        self.label_2.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.all_sentence = QtWidgets.QVBoxLayout()
        self.all_sentence.setObjectName("all_sentence")
        self.verticalLayout_2.addLayout(self.all_sentence)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.apply = QtWidgets.QPushButton(ChangeSentenceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply.sizePolicy().hasHeightForWidth())
        self.apply.setSizePolicy(sizePolicy)
        self.apply.setMaximumSize(QtCore.QSize(16777215, 39))
        self.apply.setObjectName("apply")
        self.horizontalLayout_2.addWidget(self.apply)
        self.cancel = QtWidgets.QPushButton(ChangeSentenceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setMaximumSize(QtCore.QSize(16777215, 39))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(ChangeSentenceDialog)
        QtCore.QMetaObject.connectSlotsByName(ChangeSentenceDialog)

    def retranslateUi(self, ChangeSentenceDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangeSentenceDialog.setWindowTitle(_translate("ChangeSentenceDialog", "Dialog"))
        self.label.setText(_translate("ChangeSentenceDialog", "WORD"))
        self.label_2.setText(_translate("ChangeSentenceDialog", "EDIT SENTENCE"))
        self.apply.setText(_translate("ChangeSentenceDialog", "APPLY"))
        self.cancel.setText(_translate("ChangeSentenceDialog", "CANCEL"))
