# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hand_interpreter_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InterpreterCatological(object):
    def setupUi(self, InterpreterCatological):
        InterpreterCatological.setObjectName("InterpreterCatological")
        InterpreterCatological.resize(837, 546)
        InterpreterCatological.setMinimumSize(QtCore.QSize(837, 546))
        self.centralwidget = QtWidgets.QWidget(InterpreterCatological)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 803, 519))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageFrame = QtWidgets.QLabel(self.layoutWidget)
        self.ImageFrame.setMinimumSize(QtCore.QSize(801, 411))
        #self.ImageFrame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ImageFrame.setText("")
        self.ImageFrame.setObjectName("ImageFrame")
        self.verticalLayout.addWidget(self.ImageFrame)
        self.sentence_label = QtWidgets.QLabel(self.layoutWidget)
        self.sentence_label.setMinimumSize(QtCore.QSize(801, 51))
        self.sentence_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sentence_label.setObjectName("sentence_label")
        self.verticalLayout.addWidget(self.sentence_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.word_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.word_name_label.setMinimumSize(QtCore.QSize(83, 39))
        self.word_name_label.setStyleSheet("font: 12pt \"Angsana New\";")
        self.word_name_label.setObjectName("word_name_label")
        self.horizontalLayout.addWidget(self.word_name_label)
        self.word_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.word_input.setMinimumSize(QtCore.QSize(455, 22))
        self.word_input.setObjectName("word_input")
        self.horizontalLayout.addWidget(self.word_input)
        self.frame_count_label = QtWidgets.QLabel(self.layoutWidget)
        self.frame_count_label.setMinimumSize(QtCore.QSize(96, 39))
        self.frame_count_label.setStyleSheet("font: 12pt \"Angsana New\";")
        self.frame_count_label.setObjectName("frame_count_label")
        self.horizontalLayout.addWidget(self.frame_count_label)
        self.select_frame_count = QtWidgets.QSpinBox(self.layoutWidget)
        self.select_frame_count.setMinimumSize(QtCore.QSize(44, 22))
        self.select_frame_count.setObjectName("select_frame_count")
        self.horizontalLayout.addWidget(self.select_frame_count)
        self.start_record = QtWidgets.QPushButton(self.layoutWidget)
        self.start_record.setMinimumSize(QtCore.QSize(93, 28))
        self.start_record.setObjectName("start_record")
        self.horizontalLayout.addWidget(self.start_record)
        self.verticalLayout.addLayout(self.horizontalLayout)
        InterpreterCatological.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InterpreterCatological)
        self.statusbar.setObjectName("statusbar")
        InterpreterCatological.setStatusBar(self.statusbar)
        #self.update_thread.feed_image_handinterpreter_signal.connect(self.hand_interpreter_thread.update_image)


        self.retranslateUi(InterpreterCatological)
        QtCore.QMetaObject.connectSlotsByName(InterpreterCatological)

    def retranslateUi(self, InterpreterCatological):
        _translate = QtCore.QCoreApplication.translate
        InterpreterCatological.setWindowTitle(_translate("InterpreterCatological", "AutoSign"))
        self.sentence_label.setText(_translate("InterpreterCatological", "STAGE LABEL"))
        self.word_name_label.setText(_translate("InterpreterCatological", "WORD NAME"))
        self.frame_count_label.setText(_translate("InterpreterCatological", "FRAME COUNT"))
        self.start_record.setText(_translate("InterpreterCatological", "START"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InterpreterCatological = QtWidgets.QMainWindow()
    ui = Ui_InterpreterCatological()
    ui.setupUi(InterpreterCatological)
    InterpreterCatological.show()
    sys.exit(app.exec_())
